const vscode = require('vscode');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const PRIORITY = { waiting: 3, running: 2, idle: 1 };
const norm = (p) => (process.platform === 'win32' ? path.resolve(p).toLowerCase() : path.resolve(p));

// Known agents (icons in media/, generated by scripts/make-icons.mjs; Codex uses the OpenAI mark). Anything else gets a plain spinner.
const KINDS = { claude: { label: 'Claude' }, copilot: { label: 'Copilot' }, codex: { label: 'Codex' } };
const kindOf = (agent) => (KINDS[agent] ? agent : 'other');
const labelOf = (agent) => KINDS[agent]?.label ?? (agent && agent !== 'other' ? agent : 'Agent');

function statusDir() {
  return process.env.AGENT_GROVE_STATUS_DIR || path.join(os.homedir(), '.agent-grove', 'agents');
}

/** Reads every session file and folds them into one entry per worktree root. */
function readAgents() {
  const staleMs = Math.max(1, vscode.workspace.getConfiguration('agentGrove').get('hideAfterMinutes', 10)) * 60 * 1000;
  const byRoot = new Map();
  let files = [];
  try { files = fs.readdirSync(statusDir()).filter((f) => f.endsWith('.json')); } catch { return byRoot; }
  for (const f of files) {
    try {
      const s = JSON.parse(fs.readFileSync(path.join(statusDir(), f), 'utf8'));
      const age = Date.now() - s.updatedAt;
      if (!s.agent) continue; // legacy file from before the agent field; the hook can no longer update it
      // No event for a while: the session was closed or crashed without a SessionEnd, so show no indicator at all.
      if (age > staleMs) continue;
      const key = norm(s.root);
      const cur = byRoot.get(key);
      const wins = !cur || PRIORITY[s.state] > PRIORITY[cur.state] || (PRIORITY[s.state] === PRIORITY[cur.state] && s.updatedAt > cur.updatedAt);
      byRoot.set(key, {
        state: wins ? s.state : cur.state,
        agent: wins ? s.agent : cur.agent,
        updatedAt: wins ? s.updatedAt : cur.updatedAt,
        sessions: (cur?.sessions ?? 0) + 1,
      });
    } catch { /* half-written or corrupt file */ }
  }
  return byRoot;
}

async function loadWorktrees(gitApi) {
  const seen = new Map();
  // Workspace folders plus every repository the built-in Git extension found (it scans sub-folders,
  // so opening a parent folder of several worktrees still works).
  const dirs = (vscode.workspace.workspaceFolders ?? []).map((f) => f.uri.fsPath);
  try {
    const gitExt = vscode.extensions.getExtension('vscode.git');
    const git = (gitExt?.isActive ? gitExt.exports : await gitExt?.activate())?.getAPI(1);
    for (const r of git?.repositories ?? []) dirs.push(r.rootUri.fsPath);
  } catch { /* git extension unavailable */ }
  for (const dir of dirs) {
    try {
      const repo = await gitApi.resolveRepo(dir);
      for (const w of await gitApi.listWorktrees(repo)) seen.set(norm(w.path), w);
    } catch { /* not a repo */ }
  }
  return [...seen.values()];
}

// Known agents get a brand-coloured logo from media/ (animated SVG: pulse while running, static amber while waiting).
// Codicons can't be pulsed or brand-coloured, so those states are SVGs; unknown agents use the built-in spinner.
function iconFor(a, extensionUri) {
  const known = KINDS[a.agent] ? a.agent : null;
  if (a.state === 'running') {
    return known ? vscode.Uri.joinPath(extensionUri, 'media', `${known}-pulse.svg`) : new vscode.ThemeIcon('sync~spin', new vscode.ThemeColor('charts.blue'));
  }
  if (a.state === 'waiting') {
    return known ? vscode.Uri.joinPath(extensionUri, 'media', `${known}-waiting.svg`) : new vscode.ThemeIcon('bell-dot', new vscode.ThemeColor('charts.yellow'));
  }
  return new vscode.ThemeIcon('circle-outline');
}
const describe = (a) => {
  const who = labelOf(a.agent);
  const what = { running: 'running', waiting: 'needs your input', idle: 'idle' }[a.state];
  return `${who} ${what}${a.sessions > 1 ? ` (${a.sessions} sessions)` : ''}`;
};

async function activate(context) {
  // A literal specifier lets esbuild inline lib/git.js into dist/extension.js.
  const gitApi = await import('../lib/git.js');

  let worktrees = [];
  let agents = new Map();
  const previous = new Map();
  const changed = new vscode.EventEmitter();

  const tree = vscode.window.createTreeView('agentGrove.worktrees', {
    treeDataProvider: {
      onDidChangeTreeData: changed.event,
      getChildren: () => worktrees,
      getTreeItem(w) {
        const a = agents.get(norm(w.path));
        const item = new vscode.TreeItem(w.branch ?? `detached @ ${w.head?.slice(0, 7)}`);
        item.description = a ? describe(a) : '';
        item.iconPath = a ? iconFor(a, context.extensionUri) : new vscode.ThemeIcon('git-branch');
        item.tooltip = w.path;
        item.contextValue = 'worktree';
        return item;
      },
    },
  });

  const bar = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left, 50);
  bar.command = 'agentGrove.showView';

  const findWt = (key) => worktrees.find((w) => norm(w.path) === key);

  function applyAgents() {
    // Context maps keyed by repository URI; the inline menu entries in package.json match on them with `in`.
    const running = { claude: {}, copilot: {}, codex: {}, other: {} };
    const waiting = {};
    let nRun = 0;
    let nWait = 0;
    for (const [key, a] of agents) {
      const wt = findWt(key);
      const name = wt?.branch ?? path.basename(key);
      const uri = vscode.Uri.file(wt?.path ?? key).toString();
      if (a.state === 'running') { running[kindOf(a.agent)][uri] = true; nRun++; }
      if (a.state === 'waiting') { waiting[uri] = true; nWait++; }
      const before = previous.get(key);
      if (before && before !== a.state) {
        const who = labelOf(a.agent);
        if (a.state === 'waiting') vscode.window.showInformationMessage(`${name}: ${who} needs your input`);
        else if (a.state === 'idle' && before === 'running') vscode.window.showInformationMessage(`${name}: ${who} finished`);
      }
      previous.set(key, a.state);
    }
    for (const key of [...previous.keys()]) if (!agents.has(key)) previous.delete(key);

    for (const [kind, map] of Object.entries(running)) vscode.commands.executeCommand('setContext', `agentGrove.running.${kind}`, map);
    vscode.commands.executeCommand('setContext', 'agentGrove.waiting', waiting);
    if (nRun + nWait === 0) {
      bar.hide();
    } else {
      bar.text = [nRun > 0 && `$(sync~spin) ${nRun} running`, nWait > 0 && `$(bell-dot) ${nWait} waiting`].filter(Boolean).join('  ');
      bar.show();
    }
    changed.fire();
  }

  async function refreshAll() {
    worktrees = await loadWorktrees(gitApi);
    agents = readAgents();
    applyAgents();
  }
  const pollAgents = () => { agents = readAgents(); applyAgents(); };

  fs.mkdirSync(statusDir(), { recursive: true });
  let watcher;
  try { watcher = fs.watch(statusDir(), pollAgents); } catch { /* the interval below still covers it */ }
  const poll = setInterval(pollAgents, 3000);
  const slow = setInterval(refreshAll, 15000);

  const focusView = () => vscode.commands.executeCommand('agentGrove.worktrees.focus');
  context.subscriptions.push(
    tree, bar, changed,
    { dispose: () => { watcher?.close(); clearInterval(poll); clearInterval(slow); } },
    vscode.commands.registerCommand('agentGrove.refresh', refreshAll),
    vscode.commands.registerCommand('agentGrove.installHooks', () => installHooks(context)),
    vscode.commands.registerCommand('agentGrove.showView', focusView),
    ...['claude', 'copilot', 'codex', 'other', 'waiting'].map((k) => vscode.commands.registerCommand(`agentGrove.row.${k}`, focusView)),
    vscode.commands.registerCommand('agentGrove.openInNewWindow', (w) =>
      vscode.commands.executeCommand('vscode.openFolder', vscode.Uri.file(w.path), { forceNewWindow: true })),
    vscode.commands.registerCommand('agentGrove.openTerminal', (w) =>
      vscode.window.createTerminal({ name: w.branch ?? 'worktree', cwd: w.path }).show()),
    vscode.workspace.onDidChangeWorkspaceFolders(refreshAll),
  );
  await refreshAll();
}

// Each agent has its own config file and hook format. `command` is shared; the agent and event go in as arguments.
const HOOK_TARGETS = {
  'Claude Code': {
    agent: 'claude',
    file: path.join(os.homedir(), '.claude', 'settings.json'),
    snippet: (cmd) => {
      const events = ['SessionStart', 'UserPromptSubmit', 'PostToolUse', 'Notification', 'Stop', 'SessionEnd'];
      return { hooks: Object.fromEntries(events.map((e) => [e, [{ hooks: [{ type: 'command', command: `${cmd} --agent claude` }] }]])) };
    },
  },
  'Codex CLI': {
    agent: 'codex',
    file: path.join(os.homedir(), '.codex', 'hooks.json'),
    snippet: (cmd) => {
      const events = ['SessionStart', 'UserPromptSubmit', 'PostToolUse', 'Stop'];
      return { hooks: Object.fromEntries(events.map((e) => [e, [{ hooks: [{ type: 'command', command: `${cmd} --agent codex` }] }]])) };
    },
  },
  'GitHub Copilot CLI': {
    agent: 'copilot',
    file: path.join(os.homedir(), '.copilot', 'hooks', 'agent-grove.json'),
    snippet: (cmd) => {
      const events = ['sessionStart', 'userPromptSubmitted', 'postToolUse', 'permissionRequest', 'agentStop', 'sessionEnd'];
      const hook = (e) => { const c = `${cmd} --agent copilot --event ${e}`; return { type: 'command', bash: c, powershell: c, timeoutSec: 10 }; };
      return { version: 1, hooks: Object.fromEntries(events.map((e) => [e, [hook(e)]])) };
    },
  },
};

/** Copies the bundled hook to a stable path and hands the user a config snippet (never edits agent configs itself). */
async function installHooks(context) {
  const choice = await vscode.window.showQuickPick(Object.keys(HOOK_TARGETS), { placeHolder: 'Which agent should report its status?' });
  if (!choice) return;
  const target = HOOK_TARGETS[choice];

  const hookPath = path.join(os.homedir(), '.agent-grove', 'hook.mjs');
  fs.mkdirSync(path.dirname(hookPath), { recursive: true });
  fs.copyFileSync(path.join(context.extensionPath, 'dist', 'hook.mjs'), hookPath);

  const snippet = JSON.stringify(target.snippet(`node "${hookPath.replace(/\\/g, '/')}"`), null, 2);
  await vscode.env.clipboard.writeText(snippet);

  const merge = choice === 'GitHub Copilot CLI'
    ? `Save the snippet as ${target.file} (create it if needed).`
    : `Merge its "hooks" block into ${target.file}.`;
  const pick = await vscode.window.showInformationMessage(`Hook installed and the ${choice} snippet is on your clipboard. ${merge}`, 'Open file');
  if (pick) {
    const uri = vscode.Uri.file(target.file);
    try { await vscode.window.showTextDocument(await vscode.workspace.openTextDocument(uri)); } catch (e) {
      // Only the Copilot file is ours to create; never fabricate another tool's settings file.
      if (target.agent !== 'copilot') throw e;
      await vscode.workspace.fs.createDirectory(vscode.Uri.file(path.dirname(target.file)));
      await vscode.workspace.fs.writeFile(uri, Buffer.from(''));
      await vscode.window.showTextDocument(await vscode.workspace.openTextDocument(uri));
    }
  }
}

module.exports = { activate, deactivate() {} };
